app:
  service:
      path: "./microservice-authentication"
  grpc:
    host: 0.0.0.0
    port: 7075
  mongodb:
    uri: mongodb://ery:erySRG@dbone:27020
    database: gocommerce-db
    timeoutinsecond: 10
  jwt:
    issuer: issuer
    sign-key: ErY0
    expires-seconds: 3600
  log:
    path: ./logs/